name: Geobot Setup

on:
  workflow_call:
    secrets:
      geobot_ssh_key:
        required: true
        description: "SSH key for git access"

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: geosurge-ai/geobot-ci/geobot-setup@main
        with:
          geobot_ssh_key: ${{ secrets.geobot_ssh_key }}
